# Forge mod metadata for QuickSkin
modLoader = "javafml"
loaderVersion = "[47,)"
license = "All Rights Reserved"
issueTrackerURL = "https://github.com/AkaNebur/Quick-Skin-Mod/issues"

[[mods]]
modId = "quickskin"
version = "${version}"
displayName = "Quick Skin"
displayTest = "IGNORE_ALL_VERSION"
authors = "The Plum Team"
description = '''
Change, preview, and synchronize local skins, capes, and CPM models in-game across Fabric, Forge, and NeoForge.
'''
displayURL = "https://modrinth.com/mod/quick-skin"
logoFile = "icon.png"

[[dependencies.quickskin]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.quickskin]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.20.2)"
ordering = "NONE"
side = "BOTH"

[[dependencies.quickskin]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"
