# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.java.home=C:\\Program Files\\Eclipse Adoptium\\jdk-21.0.9.10-hotspot

# Mod properties
mod_version = 2.5.6
maven_group = com.theplumteam.quick-skin
archives_name = quick-skin
enabled_platforms = fabric,neoforge

# Minecraft properties - 1.21.1
minecraft_version_1_21 = 1.21.1

# Dependencies - 1.21.1
architectury_api_version_1_21 = 13.0.6
fabric_loader_version_1_21 = 0.16.9
fabric_api_version_1_21 = 0.110.0+1.21.1
neoforge_version = 21.1.77
