pluginManagement {
    repositories {
        maven { url = 'https://maven.fabricmc.net/' }
        maven { url = 'https://maven.architectury.dev/' }
        maven { url = 'https://files.minecraftforge.net/maven/' }
        maven { url = 'https://maven.neoforged.net/releases' }
        mavenCentral()
        gradlePluginPortal()
    }
}

rootProject.name = 'quick-skin'

// 1.20.1 modules
include 'common'
include 'fabric'
include 'forge'

// 1.21.1 modules
include 'common-1.21'
include 'fabric-1.21'
include 'neoforge'
